# Generated by Django 4.0.1 on 2022-01-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(default='IT', max_length=2, primary_key=True, serialize=False, verbose_name='Abteilung_kz')),
                ('department_name', models.CharField(default='Informational Technologies', max_length=255, verbose_name='Abteilung')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('fname', models.CharField(max_length=255, verbose_name='Vorname')),
                ('lname', models.CharField(max_length=255, verbose_name='Nachname')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.department', verbose_name='Abteilung_kz')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
