# Generated by Django 4.0.1 on 2022-01-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_superuser',
            new_name='admin',
        ),
    ]
