# Generated by Django 4.0.1 on 2022-01-16 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('device_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_type_name', models.CharField(max_length=255)),
                ('device_type_shortcut', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Graphiccards',
            fields=[
                ('graphiccard_id', models.AutoField(primary_key=True, serialize=False)),
                ('graphiccard_type', models.CharField(max_length=30)),
                ('graphiccard_capacity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Graphiccards',
            },
        ),
        migrations.CreateModel(
            name='Harddisks',
            fields=[
                ('harddisk_id', models.AutoField(primary_key=True, serialize=False)),
                ('harddisk_type', models.CharField(max_length=10)),
                ('harddisk_capacity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Harddisks',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('manufacturer_shortcut', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('memory_id', models.AutoField(primary_key=True, serialize=False)),
                ('memory_type', models.CharField(max_length=20)),
                ('memory_capacity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Memories',
            },
        ),
        migrations.CreateModel(
            name='Processors',
            fields=[
                ('processor_id', models.AutoField(primary_key=True, serialize=False)),
                ('processor_name', models.CharField(max_length=30)),
                ('processor_cores', models.IntegerField()),
                ('processor_speed', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Processors',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('device_dns_name', models.CharField(blank=True, max_length=30, null=True)),
                ('device_model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(blank=True, max_length=30, null=True)),
                ('service_number', models.CharField(blank=True, max_length=30, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=30, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=30, null=True)),
                ('in_use', models.BooleanField(default=False)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='device_management.devicetype')),
                ('device_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('graphiccard_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='device_management.graphiccards')),
                ('harddisk_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='device_management.harddisks')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='device_management.manufacturer')),
                ('memory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='device_management.memories')),
                ('processor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='device_management.processors')),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
